# Generated by Django 3.1.1 on 2020-09-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tests',
            new_name='Test',
        ),
    ]
