# Generated by Django 3.1.1 on 2020-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20200926_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('submitted_ans', models.CharField(max_length=1)),
                ('obtained_marks', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('test_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('mark', models.IntegerField()),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('correct_ans', models.CharField(max_length=1)),
            ],
        ),
    ]
