# Generated by Django 3.1.1 on 2020-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_answer_attempt_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(max_length=100),
        ),
    ]
