# Generated by Django 3.1.1 on 2020-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_auto_20200930_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted_ans',
            field=models.CharField(max_length=100),
        ),
    ]
