# Generated by Django 3.1.1 on 2020-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0007_auto_20200930_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='submited',
            field=models.BooleanField(default=False),
        ),
    ]
