# Generated by Django 3.1.1 on 2020-09-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_test_submited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='submited',
        ),
        migrations.AddField(
            model_name='attempt',
            name='submited',
            field=models.BooleanField(default=False),
        ),
    ]
