# Generated by Django 3.1.1 on 2020-09-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_auto_20200930_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='submited',
            new_name='submitted',
        ),
    ]
