# Generated by Django 3.1.1 on 2020-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0010_auto_20200930_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='multipleAttampts',
            field=models.BooleanField(default=True),
        ),
    ]
