# Generated by Django 3.1.1 on 2020-10-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0011_test_multipleattampts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='multipleAttampts',
            new_name='multipleAttempts',
        ),
    ]
