# Generated by Django 3.1.1 on 2020-10-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0012_auto_20201002_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
